#if !canImport(ObjectiveC)
import XCTest

extension Asn1DerCoderTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Asn1DerCoderTest = [
        ("testOk", testOk),
    ]
}

extension Asn1DerTestErr {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Asn1DerTestErr = [
        ("testBooleanErr", testBooleanErr),
        ("testIntegerErr", testIntegerErr),
        ("testLengthErr", testLengthErr),
        ("testNullErr", testNullErr),
        ("testObjectErr", testObjectErr),
        ("testOctetStringErr", testOctetStringErr),
        ("testSequenceErr", testSequenceErr),
        ("testUTF8StringErr", testUTF8StringErr),
    ]
}

extension Asn1DerTestOk {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Asn1DerTestOk = [
        ("testBooleanOk", testBooleanOk),
        ("testExample", testExample),
        ("testIntegerOk", testIntegerOk),
        ("testLengthOk", testLengthOk),
        ("testNullOk", testNullOk),
        ("testObjectOk", testObjectOk),
        ("testOctetStringOk", testOctetStringOk),
        ("testSequenceOk", testSequenceOk),
        ("testUTF8StringOk", testUTF8StringOk),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Asn1DerCoderTest.__allTests__Asn1DerCoderTest),
        testCase(Asn1DerTestErr.__allTests__Asn1DerTestErr),
        testCase(Asn1DerTestOk.__allTests__Asn1DerTestOk),
    ]
}
#endif
